version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always

  sql-insert:
    image: sql-insert
    build: images/sql-insert
    command: ["python", "./sql-insert.py"]
    depends_on:
      - database
    links:
      - database:database
    volumes:
      - ./data:/data

  sql-read:
    image: sql-read
    build: images/sql-read
    command: ["python", "./sql-read.py"]
    depends_on:
      - database
    links:
      - database:database
    volumes:
      - ./data:/data      
     